django-project-avito/avdito/avdito/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('doska.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-project-avito/avdito/core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import CustomLoginView, CustomLogoutView, SignupView, ProfileView, ProfileEditView, AddFriendView, \
    CustomPasswordResetView, CustomPasswordResetViewDone, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'core'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('edit-profile/<int:user_id>/', login_required(ProfileEditView.as_view()), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/', login_required(AddFriendView.as_view()), name='add_remove_friend'),

    # password reset
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetViewDone.as_view(), name='password_reset_done'),
    path('password-reset/<str:uidb64>/<slug:token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

django-project-avito/avdito/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block static_files %}
        <link rel="stylesheet" href="{% static 'common/css/index.css' %}" type="text/css">
    {% endblock static_files %}
    <title>
        {% block title %}
            ADVITO
        {% endblock title %}
    </title>
</head>
<body class="page">
    <header class="header">
        <nav class="menu">
        {% block login %}
            {% if not user.is_authenticated %}
                <p class="menu__item"><a href="{% url 'core:login' %}">Login</a></p>
                <p class="menu__item"><a href="{% url 'core:signup' %}">Register</a></p>
            {% else %}
                <p class="menu__item"><a href="{% url 'core:edit_profile' user.id %}">Update profile</a></p>
                <form method="post" action="{% url 'core:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="menu__item">Exit</button>
                </form>
            {% endif %}
        {% endblock login %}
        </nav>
    </header>
    <div class="content">
    {% block page %}

    {% endblock page %}
    </div>
    <footer class="footer">

    </footer>
</body>
</html>