django-project-avito/avdito/avdito/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('doska.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-project-avito/avdito/core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import CustomLoginView, CustomLogoutView, SignupView, ProfileView, ProfileEditView, AddFriendView, \
    CustomPasswordResetView, CustomPasswordResetViewDone, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'core'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('edit-profile/<int:user_id>/', login_required(ProfileEditView.as_view()), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/', login_required(AddFriendView.as_view()), name='add_remove_friend'),

    # password reset
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetViewDone.as_view(), name='password_reset_done'),
    path('password-reset/<str:uidb64>/<slug:token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

django-project-avito/avdito/doska/urls.py
from django.urls import path
from .views import index, announcement_create, announcement_detail, DeleteAnnouncementView

app_name = "doska"

urlpatterns = [
    path(r'', index, name='index'),
    path('create/', announcement_create, name='announcement_create'),
    path('detail/<int:announcement_id>/', announcement_detail, name="detail"),
    path('delete/<int:announcement_id>/', DeleteAnnouncementView.as_view(), name="delete"),
]

django-project-avito/avdito/doska/models.py
from django.db import models
from core.models import CustomUser
from django.urls import reverse


def avatar_announcement_path(instance, filename):
    return f'announcement_{instance.author.id}/avatar/{filename}'


class Announcement(models.Model):
    # Объявление
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    avatar = models.ImageField(upload_to=avatar_announcement_path, default=None)

    def __str__(self):
        return f"Announcement from {self.author.username}"

    def get_absolute_url(self):
        return reverse('doska:detail', args=(self.id,))

django-project-avito/avdito/doska/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Announcement


class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ['avatar', 'title', 'description']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image.size >= 5 * 1024 * 1024:
            raise ValidationError("File is too big!", code='size_error')

        return image

django-project-avito/avdito/doska/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, PasswordResetView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DeleteView

from .forms import AnnouncementForm
from .models import Announcement


# Create your views here.


def index(request):
    announcements = Announcement.objects.all()
    context = {
        "header": "Ваши объявления",
        "announcements": announcements,
    }
    return render(request, 'index.html', context)


def advt(request):
    return HttpResponse('Second view return')


@login_required
def announcement_create(request):
    if request.method == 'GET':
        form = AnnouncementForm()
    else:
        form = AnnouncementForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(post.get_absolute_url())

    context = {
        "header": "Create announcement",
        'form': form
    }
    return render(request, 'anno_create.html', context)


def announcement_detail(request, announcement_id):
    announcement = get_object_or_404(Announcement, id=announcement_id)
    header = f"Announcement: {announcement.title}"

    context = {
        "header": header,
        "announcement": announcement,
    }
    return render(request, 'detail.html', context)


class DeleteAnnouncementView(DeleteView):
    model = Announcement
    pk_url_kwarg = "announcement_id"
    template_name = "anno_delete.html"
    success_url = reverse_lazy('doska:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['header'] = f"Delete announcement #{self.object.id}"
        context['description'] = "description"
        return context

    # def get_success_url(self):
    #     return reverse('post:index')

    @method_decorator(login_required)
    def post(self, *args, **kwargs):
        object = self.get_object()

        if self.request.user == object.author:
            return super().post(self, *args, **kwargs)
        else:
            raise PermissionDenied("You are not the author of this content")

django-project-avito/avdito/doska/templates/anno_create.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}


{% block page %}
    <h1>{{ header }}</h1>
    <form action="{% url 'doska:announcement_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create post">
    </form>
{% endblock page %}

django-project-avito/avdito/doska/templates/anno_delete.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}


{% block page %}
    <h1>{{ header }}</h1>
    <p>{{description}}</p>
    <form action="{% url 'doska:delete' announcement.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="delete announcement">
    </form>
{% endblock page %}

django-project-avito/avdito/doska/templates/anno_info.html
<div class="post">
    {% if request.path == post.get_absolute_url %}
    <h2>Title: {{ post.title }}</h2>
    {% else %}
    <h2>Title: <a href="{{ doska.get_absolute_url }}">{{ announcement.title }}</a></h2>
    {% endif %}
    <p>Author: <a href="{% url 'core:profile' announcement.author.id %}">{{ announcement.author }}</a></p>
    <p>Description: {{ announcement.description }}</p>
    <img style="width: 100px" src="{{ announcement.avatar.url }}" alt="{{ announcement.title }}">
    {% if request.user.is_authenticated and request.user == announcement.author %}
    <a href="{% url 'doska:delete' announcement.id %}">X</a>
    {% endif %}
</div>

django-project-avito/avdito/doska/templates/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}


{% block page %}
    <h1>{{ header }}</h1>
    <a href="{% url 'doska:index' %}">На главную</a>
    {% if announcement %}
        {% include 'anno_info.html' %}
    {% endif %}
{% endblock page %}

django-project-avito/avdito/doska/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block static_files %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'doska/css/index.css' %}" type="text/css">
{% endblock static_files %}

{% block title %}
{{ header }}
{% endblock title %}


{% block page %}
<h1>{{ header }}</h1>
{% if announcements %}
<ul class="announcement">
    {% for announcement in announcements %}
    <li class="announcement__item">
        {% include 'anno_info.html' %}
    </li>
    {% endfor %}
</ul>
{% else %}
<h2>Объявлений нет!</h2>
<a href="{% url 'doska:announcement_create' %}">Создать объявление</a>
{% endif %}

{% endblock page %}

django-project-avito/avdito/doska/templates/login.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block login %}
{% endblock login %}

{% block page %}
    <h1>{{ header }}</h1>
    <form action="{% url 'doska:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <h2>Забыли пароль?</h2>
    <p><a href="{% url 'doska:password_reset' %}">Восстановить пароль</a></p>
{% endblock page %}

django-project-avito/avdito/doska/templates/signup.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block login %}
{% endblock login %}

{% block page %}
    <h1>{{ header }}</h1>
    <form action="{% url 'doska:signup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signup">
    </form>
{% endblock page %}