django-project-avito/avdito/avdito/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'', include('doska.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-project-avito/avdito/core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import CustomLoginView, CustomLogoutView, SignupView, ProfileView, ProfileEditView, AddFriendView, \
    CustomPasswordResetView, CustomPasswordResetViewDone, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'core'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/<int:user_id>/', ProfileView.as_view(), name='profile'),
    path('edit-profile/<int:user_id>/', login_required(ProfileEditView.as_view()), name='edit_profile'),
    path('profile/<int:user_id>/add-remove-friend/', login_required(AddFriendView.as_view()), name='add_remove_friend'),

    # password reset
    path('password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', CustomPasswordResetViewDone.as_view(), name='password_reset_done'),
    path('password-reset/<str:uidb64>/<slug:token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

django-project-avito/avdito/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    about = models.TextField(max_length=1000, blank=True)
    avatar = models.ImageField(upload_to="profile")
    phone_number = models.CharField(max_length=11, blank=True, null=True)

    def __str__(self):
        return str(self.username)

django-project-avito/avdito/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.utils.translation import gettext_lazy as _

from core.models import CustomUser


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'placeholder': _('Username'),
        'class': 'form-control',
    }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': 'form-control',
        }),
    )


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "avatar", "about")

django-project-avito/avdito/core/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, UpdateView

from .forms import LoginForm, SignupForm
from .models import CustomUser


class CustomLoginView(LoginView):
    form_class = LoginForm
    template_name = 'core/login.html'
    next_page = reverse_lazy('doska:index')
    extra_context = {'header': 'Login'}
    redirect_authenticated_user = True


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('doska:index')
    http_method_names = ['post', ]


class SignupView(View):
    template_name = 'core/signup.html'
    form = SignupForm

    def get_context_data(self):
        context = {
            'header': 'Signup',
            'form': self.form,
        }
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST, request.FILES)
        context = self.get_context_data()
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('doska:index'))
        else:
            return render(request, self.template_name, context)


class ProfileView(DetailView):
    model = CustomUser
    template_name = 'core/profile.html'
    pk_url_kwarg = 'user_id'

    def get_context_data(self, **kwargs):
        object = self.get_object()
        context = super().get_context_data(**kwargs)
        context['header'] = f'Profile of {object.username}'
        return context


class ProfileEditView(UpdateView):
    model = CustomUser
    template_name = 'core/edit_profile.html'
    pk_url_kwarg = 'user_id'
    fields = ['first_name', 'last_name', 'email', 'birth_date', 'about', 'avatar', 'phone_number']

    def get_context_data(self, **kwargs):
        object = self.get_object()
        context = super().get_context_data(**kwargs)
        context['header'] = f'Update profile of {object.username}'
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object != request.user:
            raise PermissionDenied("You can't edit this profile info!")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        object = self.get_object()
        return reverse('core:profile', kwargs={'user_id': object.id})


class AddFriendView(View):
    http_method_names = ['post', ]

    def post(self, request, user_id, *args, **kwargs):
        friend = get_object_or_404(CustomUser, id=user_id)
        me = request.user

        if me.friends.filter(id=friend.id).exists():
            me.friends.remove(friend)
        else:
            me.friends.add(friend)
        return redirect(request.META.get('HTTP_REFERER'), request)


class CustomPasswordResetView(PasswordResetView):
    success_url = reverse_lazy("core:password_reset_done")
    template_name = "core/password_reset/password_reset_form.html"
    email_template_name = "core/password_reset/password_reset_email.html"
    subject_template_name = "core/password_reset/subject_template_name.txt"


class CustomPasswordResetViewDone(PasswordResetDoneView):
    template_name = "core/password_reset/password_reset_done.html"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("core:password_reset_complete")


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "core/password_reset/password_reset_complete.html"

django-project-avito/avdito/core/templates/core/edit_profile.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block page %}
    <h1>{{ header }}</h1>
    {% if customuser.avatar %}
        <img style="width: 100px" src="{% if customuser.avatar %}{{ customuser.avatar.url }}{% else %}#{% endif %}" alt="{{ customuser.username }}"/>
    {% else %}
        <p>You don't have avatar!</p>
    {% endif %}

    <h2>Update your info if you wanna :)</h2>
    <form action="{% url 'core:edit_profile' customuser.id  %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update profile</button>
    </form>


{% endblock page %}

django-project-avito/avdito/core/templates/core/login.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block login %}
{% endblock login %}

{% block page %}
    <h1>{{ header }}</h1>
    <form action="{% url 'core:login' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <h2>Забыли пароль?</h2>
    <p><a href="{% url 'core:password_reset' %}">Восстановить пароль</a></p>
{% endblock page %}

django-project-avito/avdito/core/templates/core/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block page %}
    <h1>{{ header }}</h1>
    <h2>User info</h2>
    <p>Firstname: {{customuser.first_name}}</p>
    <p>Lastname: {{customuser.last_name}}</p>
    <p>About: {{customuser.about}}</p>
    <img style="width: 100px" src="{% if customuser.avatar %}{{ customuser.avatar.url }}{% else %}#{% endif %}" alt="{{ customuser.username }}"/>

    {% if user.is_authenticated and customuser.id != user.id %}
        <form action="{% url 'core:add_remove_friend' customuser.id %}" method="post">
            {% csrf_token %}
            {% if customuser in user.friends.all %}
                <button type="submit">Удалить из друзей</button>
            {% else %}
                <button type="submit">Добавить в друзья</button>
            {% endif %}
        </form>
    {% endif %}

    <h2>User posts:</h2>
    {% for post in customuser.posts.all %}
        {% include 'post/post_short_info.html' %}
    {% endfor %}
{% endblock page %}

django-project-avito/avdito/core/templates/core/signup.html
{% extends 'base.html' %}

{% block title %}
    {{ header }}
{% endblock title %}

{% block login %}
{% endblock login %}

{% block page %}
    <h1>{{ header }}</h1>
    <form action="{% url 'core:signup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signup">
    </form>
{% endblock page %}